name: sat_sen_app
description: "Weather app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  responsive_framework: ^1.1.1
  percent_indicator: ^4.2.5
  package_info_plus: ^4.1.0
  get_it: ^7.6.4
  path_provider: ^2.1.1
  pointycastle: ^3.7.3
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  url_launcher: ^6.1.14
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^17.2.1+2
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  firebase_performance: ^0.9.2+7
  asn1lib: ^1.5.0
  formz: ^0.4.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_timezone: ^4.1.1
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  intl: any
  android_id: ^0.4.0
  device_info_plus: ^10.1.1
  dart_des: ^1.0.2
  json_annotation: ^4.8.1
  connectivity_plus: ^6.1.0
  easy_localization: ^3.0.5
  flutter_dotenv: ^6.0.0
  html: ^0.15.6
  flutter_html: ^3.0.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
